# Generated by Django 3.0.3 on 2020-06-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=55)),
                ('address', models.CharField(max_length=55)),
                ('college', models.CharField(max_length=55)),
                ('mail', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('called_time', models.DateTimeField()),
                ('image_recieved', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=12)),
            ],
        ),
    ]
